# 배포 시에 파일 내용이 변경될 예정임
# H2 -> MySQL

spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url:  jdbc:h2:~/puruboard
    driver-class-name: org.h2.Driver
    username: sa
    password:
    generate-unique-name: false

  jpa:
    datasource-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # Spring Boot 서버가 시작될 때마다 테이블을 새로 만든다
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

logging:
  level:
    noticeboard.starry: debug