# 배포: MySQL

spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://puruboard.c7vxa3pl24ox.ap-northeast-2.rds.amazonaws.com:3306/puruboard
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: babybeb
    password: ods030207
    generate-unique-name: false

  jpa:
    datasource-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

logging:
  level:
    noticeboard.starry: debug